# Generated by Django 3.1.3 on 2021-01-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_option_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='letter',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
    ]
