# Generated by Django 3.1.3 on 2021-01-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210127_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serving',
            old_name='date',
            new_name='day',
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
